#!/bin/bash

set -eo pipefail

if [ -z "${POSTGRES_USER}" ] || [ -z "${POSTGRES_PASSWORD}" ] || [ -z "${POSTGRES_HOST}" ] || [ -z "${POSTGRES_DB}" ];then
  echo "Database vars not set"
  exit 1
fi

export POSTGRES_PORT="${POSTGRES_PORT:-5432}"
echo "# Postgres DB is ${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

export LEMUR_ADMIN_PASSWORD="${LEMUR_ADMIN_PASSWORD:-admin}"

export SQLALCHEMY_DATABASE_URI="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB"

echo " # POSTGRES_DB_MODE was neither 'load-from-dump' nor 'init', so will use existing database"
# for first time use, init should not touched exists data
cd /opt/lemur/lemur
/opt/venv/bin/python3 /opt/lemur/lemur/manage.py --config=/home/lemur/.lemur/lemur.conf.py init -p "${LEMUR_ADMIN_PASSWORD}"

echo " # Done"

exec "$@"
